plugins {
    id 'fabric-loom' version '1.14.10'
    id 'maven-publish'
}

version = project.mod_version
group = 'jp.exnakamura'

base {
    archivesName = project.archives_base_name
}

repositories {}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.11'
    mappings 'net.fabricmc:yarn:1.21.11+build.1:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.19.2'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.141.3+1.21.11'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.encoding = 'UTF-8'
}


tasks.withType(AbstractArchiveTask).configureEach {
    archiveVersion = "v${project.mod_version}"
}
